# This file specifies which controllers MoveIt should connect to when executing commands.
# It specifies the name, and the type of the underlying controller (note the namespace needs to be correct so the topic names match)
# The controller types are a bit different than ros2_control, but FollowJointTrajectory matches with ros2_control's JointTrajectoryController
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_trajectory_controller
    - gripper_trajectory_controller

  arm_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"

  gripper_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - "6"